baseURL = 'https://readchina.github.io/comics/'
languageCode = 'en-us'
title = 'Comics'
theme = "hugo-book"

# Book configuration
enableGitInfo = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo = 'logo.svg'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/readchina/comics'

[markup.goldmark.renderer]
  unsafe = true  

BookPortableLinks = true
